

from abc import ABC, abstractmethod
from typing import Callable
from .Inheritance import DataClass


class DecoratorSkeleton(ABC):
    @abstractmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @abstractmethod
    def __call__(self, func: Callable) -> Callable: ...
    ...


class Initializer(DecoratorSkeleton):
    __texture: str
    __args: tuple[any, ...]
    __kwargs: dict[str, any]

    @property
    def args(self) -> tuple[any, ...]: ...
    @property
    def kwargs(self) -> dict[str, any]: ...

    def __init__(self, *args, **kwargs): ...
    def __repr__(self) -> str: ...
    def __call__(self, func: Callable) -> Callable: ...

    ...

class Test(DataClass):
    texture: str
    class Repeat(DecoratorSkeleton):
        __process_number: int
        __number_of_times: int
        def __init__(self, _number_of_times: int): ...
        @classmethod
        def start_process(cls) -> None: ...
        @classmethod
        def end_process(cls) -> None: ...
        def __call__(self, _func: Callable) -> Callable: ...
        ...
    class Time(DecoratorSkeleton):
        __target: Callable
        def __init__(self, _func: Callable): ...
        def __call__(self, *args, **kwargs) -> any: ...
        ...
    class BlankLine(DecoratorSkeleton):
        __func: Callable
        def __init__(self, _func: Callable[]): ...
        def __call__(self, *args, **kwargs) -> Callable: ...
    ...
