

from .Inheritance import InheritanceSkeleton


class FunctionsSkeleton(InheritanceSkeleton): ...

class Convert(FunctionsSkeleton):
    def index_from(self, _position: tuple[int, int], length: int) -> int: ...
    def position_from(self, _index: int, _length: int) -> tuple[int, int]: ...
    ...
